/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import React from "react";
import { PolicyTopic } from "@/types/policy";
import {
  Calendar, ShieldCheck, Users, Clock, Sparkles, GraduationCap,
  Wallet, TrendingDown, CreditCard, FileCheck, PiggyBank,
  Calculator, Gift, FileSpreadsheet, Briefcase, HeartPulse,
  Baby, Car, Zap, Shield, AlertTriangle, Trees, BookOpen, Hotel, Home, Ban, MapPin,
  TrendingUp, ShieldAlert, Sun, Scale, Smartphone
} from "lucide-react";

interface PolicyHighlightCardsProps {
  policy: PolicyTopic;
  isSimpleMode: boolean;
}

export const PolicyHighlightCards: React.FC<PolicyHighlightCardsProps> = ({
  policy,
  isSimpleMode,
}) => {
  const cardDataMap: Record<string, any[]> = {
    "child-allowance-expansion": [
      {
        label: isSimpleMode ? "もらえる年齢" : "対象年齢の延長",
        value: "18歳",
        unit: "まで",
        oldValue: "これまで 15歳（中学生）",
        description: isSimpleMode ? "高校生ももらえるように！" : "高校生年代の3年間が追加",
        badge: "3年間延長",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Calendar,
      },
      {
        label: isSimpleMode ? "親のきゅうりょう制限" : "所得制限",
        value: "なし",
        unit: "（撤廃）",
        oldValue: "これまで 年収制限あり",
        description: isSimpleMode ? "だれでも全員もらえる！" : "親の年収に関わらず全員支給",
        badge: "完全撤廃",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "3人目のこどもの金額" : "第3子以降の手当",
        value: "30,000",
        unit: "円/月",
        oldValue: "これまで 月15,000円",
        description: isSimpleMode ? "3人目からは2ばいに！" : "多子世帯の支援を倍増",
        badge: "金額が2倍",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Users,
      },
      {
        label: isSimpleMode ? "もらえる回数" : "支給回数",
        value: "年 6",
        unit: "回",
        oldValue: "これまで 年3回（4ヶ月毎）",
        description: isSimpleMode ? "2ヶ月ごとに届いて安心！" : "偶数月に2ヶ月分ずつ支給",
        badge: "隔月支給",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Clock,
      },
    ],
    "university-tuition-waiver": [
      {
        label: isSimpleMode ? "免除されるお金" : "授業料の減免上限",
        value: "約 70",
        unit: "万円/年",
        oldValue: "私立大は約70万、国公立は約54万円",
        description: isSimpleMode ? "大学の授業料が無料に！" : "国が定める上限まで免除",
        badge: "私立年70万円",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: GraduationCap,
      },
      {
        label: isSimpleMode ? "対象になる条件" : "対象世帯",
        value: "3人",
        unit: "扶養",
        oldValue: "子ども3人以上を同時に扶養",
        description: isSimpleMode ? "3人以上育てている家庭" : "多子世帯の全兄弟が対象",
        badge: "多子世帯限定",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "親のきゅうりょう制限" : "所得制限",
        value: "なし",
        unit: "（撤廃）",
        oldValue: "これまで年収約380万円未満のみ",
        description: isSimpleMode ? "年収に関係なく使える！" : "どの年収層でも利用可能",
        badge: "完全撤廃",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "いつから始まる？" : "制度の開始時期",
        value: "2025",
        unit: "年4月〜",
        oldValue: "令和7年度から正式スタート",
        description: isSimpleMode ? "在学生も新入生も対象！" : "2025年度春学期から適用",
        badge: "令和7年度〜",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Clock,
      },
    ],
    "income-barrier": [
      {
        label: isSimpleMode ? "税金がとられるライン" : "103万円の壁（所得税）",
        value: "103",
        unit: "万円",
        oldValue: "30年間据え置きの基準",
        description: isSimpleMode ? "178万円へ引き上げの議論中！" : "178万円等への引上げを審議中",
        badge: "税制改正議論",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "保険に入るライン（大企業）" : "106万円の壁（社会保険）",
        value: "106",
        unit: "万円",
        oldValue: "従業員51人以上の企業等",
        description: isSimpleMode ? "超えると手取りがガクンと減る" : "厚生年金・健保の加入義務",
        badge: "手取りの崖①",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: TrendingDown,
      },
      {
        label: isSimpleMode ? "扶養から外れるライン" : "130万円の壁（扶養外れ）",
        value: "130",
        unit: "万円",
        oldValue: "全企業共通の扶養基準",
        description: isSimpleMode ? "親や夫の保険から完全に外れる" : "国民年金・国保の自己負担発生",
        badge: "手取りの崖②",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "急に減ってしまう手取り" : "社保加入時の手取り減",
        value: "約 16",
        unit: "万円",
        oldValue: "年金＋健康保険料（年間）",
        description: isSimpleMode ? "このために仕事を休む人が続出" : "働き控えの最大の原因",
        badge: "逆転現象",
        badgeColor: "bg-purple-100 text-purple-800",
        icon: ShieldCheck,
      },
    ],
    "myna-health-insurance": [
      {
        label: isSimpleMode ? "昔の保険証のあつかい" : "従来の健康保険証",
        value: "完全失効",
        unit: "（利用不可）",
        oldValue: "2024年12月に新規発行終了",
        description: isSimpleMode ? "いまはもう昔の保険証は使えません" : "紙・プラスチック保険証はすべて失効",
        badge: "完全終了",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: CreditCard,
      },
      {
        label: isSimpleMode ? "1年間のゆうよ期間" : "経過措置（猶予期間）",
        value: "終了済",
        unit: "（2025/12/1）",
        oldValue: "最長1年間の経過措置期間",
        description: isSimpleMode ? "手元の保険証が使えた期間も終了！" : "2025年12月1日をもって猶予終了",
        badge: "完全移行済",
        badgeColor: "bg-slate-100 text-slate-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "マイナを使わない人の受診" : "「資格確認書」の手続き",
        value: "要申請",
        unit: "（会社・役所）",
        oldValue: "待っていても届かないため申請が必要",
        description: isSimpleMode ? "申請すればこれまで通り受診OK！" : "健保や自治体に申請して交付を受ける",
        badge: "健保・役所へ申請",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "高額な医療費の手続き" : "限度額適用認定証",
        value: "事前申請",
        unit: "なし（マイナ）",
        oldValue: "マイナなら窓口同意で自動適用",
        description: isSimpleMode ? "マイナなら数十万円の立て替えゼロ！" : "資格確認書は従来通り事前申請が必要",
        badge: "マイナの利点",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: FileCheck,
      },
    ],
    "new-nisa": [
      {
        label: isSimpleMode ? "一生で非課税にできる上限" : "生涯非課税保有限度額",
        value: "1,800",
        unit: "万円",
        oldValue: "旧つみたてNISA最大800万円",
        description: isSimpleMode ? "売れば枠が復活して再利用可能！" : "簿価（買付残高）ベースで枠再利用可",
        badge: "生涯枠拡大",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: PiggyBank,
      },
      {
        label: isSimpleMode ? "税金がタダになる期間" : "非課税保有期間",
        value: "無期限",
        unit: "（恒久化）",
        oldValue: "旧制度は5年または20年限定",
        description: isSimpleMode ? "一生涯ずっと税金ゼロで運用！" : "ロールオーバー手続き不要で完全恒久化",
        badge: "恒久化",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "1年間に投資できる上限" : "年間投資枠",
        value: "360",
        unit: "万円/年",
        oldValue: "旧制度は年40万〜120万円",
        description: isSimpleMode ? "つみたてと成長枠を一緒に使える！" : "つみたて120万＋成長投資240万の併用",
        badge: "併用可能",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "浮く税金の割合" : "非課税メリット率",
        value: "20.315",
        unit: "%",
        oldValue: "通常口座は利益の2割を課税",
        description: isSimpleMode ? "本来引かれる税金がまるまる手元に" : "所得税15.315%＋住民税5%が全額免除",
        badge: "まるまる手取り",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Wallet,
      },
    ],
    "fixed-tax-cut": [
      {
        label: isSimpleMode ? "1人あたりの減税合計額" : "定額減税（所得税＋住民税）",
        value: "40,000",
        unit: "円/人",
        oldValue: "所得税3万円＋住民税1万円",
        description: isSimpleMode ? "家族の人数分だけ手取りが増える！" : "納税者本人＋扶養家族1人につき4万円",
        badge: "1人4万円",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Calculator,
      },
      {
        label: isSimpleMode ? "子ども・配偶者のカウント" : "扶養親族の対象",
        value: "16歳未満",
        unit: "も含む",
        oldValue: "税法上の年少扶養も人数に合算",
        description: isSimpleMode ? "赤ちゃんや子どもも全員対象！" : "同一生計配偶者および扶養親族全員",
        badge: "子どもも対象",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "税金が足りない人の救済" : "調整給付金（補足給付）",
        value: "1万円単位",
        unit: "で切り上げ",
        oldValue: "税額不足分は現金で振込",
        description: isSimpleMode ? "引ききれない分は自治体から届く！" : "減税しきれない差額を切り上げ給付",
        badge: "現金給付",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "税金を払っていない世帯" : "低所得・非課税世帯措置",
        value: "7〜10",
        unit: "万円/世帯",
        oldValue: "減税の代わりに先行給付",
        description: isSimpleMode ? "住民税非課税世帯には別途給付金！" : "子ども加算（1人5万円）等の物価高給付",
        badge: "重点支援給付",
        badgeColor: "bg-slate-100 text-slate-800",
        icon: ShieldCheck,
      },
    ],
    "furusato-tax": [
      {
        label: isSimpleMode ? "実質の自己負担額" : "寄附金控除の最低自己負担",
        value: "2,000",
        unit: "円",
        oldValue: "上限額内なら何自治体でも2,000円",
        description: isSimpleMode ? "自己負担2千円でいろんな特産品が！" : "住民税等の税額控除を受ける最低負担額",
        badge: "実質2,000円",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Gift,
      },
      {
        label: isSimpleMode ? "ポータルサイトのポイント" : "仲介サイトのポイント付与",
        value: "全面禁止",
        unit: "（2025/10〜）",
        oldValue: "以前は10〜20%還元も横行",
        description: isSimpleMode ? "サイト独自ポイントは付かなくなりました" : "総務省告示により自治体契約サイトで禁止",
        badge: "新ルール施行",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "もらえる返礼品の目安" : "返礼品調達割合ルール",
        value: "3割",
        unit: "以下",
        oldValue: "寄附金額に対する仕入れ価格基準",
        description: isSimpleMode ? "寄附した額の3割相当の品が届く" : "地場産品基準および返礼品調達費3割制限",
        badge: "3割基準",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "町の経費の上限" : "募集経費5割ルールの厳格化",
        value: "5割",
        unit: "以下",
        oldValue: "ワンストップ特例事務費等も合算",
        description: isSimpleMode ? "寄附金の半分は確実に地域づくりへ！" : "隠れ経費の排除により制度の健全化を徹底",
        badge: "経費適正化",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: FileCheck,
      },
    ],
    "invoice-system": [
      {
        label: isSimpleMode ? "小規模事業者の特別ルール" : "2割特例（激変緩和措置）",
        value: "売上税額の20%",
        unit: "のみ納税",
        oldValue: "本来は仕入税額控除の計算が必要",
        description: isSimpleMode ? "売上の約1.8%の税金を納めればOK！" : "免税から課税転換した事業者の負担軽減",
        badge: "特例措置",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: FileSpreadsheet,
      },
      {
        label: isSimpleMode ? "登録しない場合の猶予" : "仕入税額控除の経過措置",
        value: "80%控除",
        unit: "（〜2026/9）",
        oldValue: "免税事業者からの仕入でも控除可能",
        description: isSimpleMode ? "取引先もいきなり全額負担にはならない" : "2026年10月以降は50%控除へ段階的縮小",
        badge: "経過措置中",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "一般の消費者を相手にする人" : "一般消費者向け（BtoC）",
        value: "免税維持",
        unit: "も可能",
        oldValue: "客がインボイスを求めない場合",
        description: isSimpleMode ? "相手が会社でなければ登録しなくてOK！" : "美容院・飲食店・一般向け整体等の選択肢",
        badge: "BtoCは免税可",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "登録した人の手続き" : "確定申告・帳簿保存義務",
        value: "年1回",
        unit: "消費税申告",
        oldValue: "これまで免税なら申告不要だった",
        description: isSimpleMode ? "所得税とは別に消費税の計算が必要" : "簡易課税や2割特例での申告手続きが発生",
        badge: "事務負担増",
        badgeColor: "bg-slate-100 text-slate-800",
        icon: FileCheck,
      },
    ],
    "pension-start-age": [
      {
        label: isSimpleMode ? "もらい始められる年齢の幅" : "受給開始の選択可能年齢",
        value: "60〜75",
        unit: "歳",
        oldValue: "以前は60〜70歳までだった",
        description: isSimpleMode ? "自分の生活に合わせて自由に決められる！" : "65歳標準受給から前後15年間の選択制",
        badge: "60〜75歳",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Calendar,
      },
      {
        label: isSimpleMode ? "75歳まで遅らせた場合の増額" : "最大増額率（75歳受給開始）",
        value: "+84",
        unit: "%",
        oldValue: "1ヶ月遅らせるごとに+0.7%増",
        description: isSimpleMode ? "一生もらえる年金がほぼ2倍に！" : "繰下げにより生涯増額された年金を受給",
        badge: "最大+84%",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "60歳まで早めた場合の減額" : "最大減額率（60歳受給開始）",
        value: "-24",
        unit: "%",
        oldValue: "1ヶ月早めるごとに-0.4%減",
        description: isSimpleMode ? "早くもらえる代わりに一生減額される" : "2022年法改正で減額率が月0.5%から0.4%へ緩和",
        badge: "最大-24%",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: TrendingDown,
      },
      {
        label: isSimpleMode ? "元が取れる年齢（損益分岐点）" : "繰下げの損益分岐年齢",
        value: "約 82",
        unit: "歳",
        oldValue: "受給開始から約12年で総額逆転",
        description: isSimpleMode ? "長生きするなら遅らせた方がトク！" : "70歳開始なら81歳11ヶ月以上生存で有利",
        badge: "長寿リスク対策",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Clock,
      },
    ],
    "zaishoku-pension": [
      {
        label: isSimpleMode ? "年金が減らされない給料ライン" : "支給停止基準額（月額合算）",
        value: "50",
        unit: "万円/月",
        oldValue: "給与（総報酬目安）＋厚生年金月額",
        description: isSimpleMode ? "合計月50万円までは年金を満額もらえる！" : "2024年度より基準額が50万円に改定",
        badge: "月50万円基準",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Briefcase,
      },
      {
        label: isSimpleMode ? "50万円を超えた分のカット割合" : "超過分の支給停止率",
        value: "1/2",
        unit: "カット",
        oldValue: "（総収入 - 50万円）÷ 2",
        description: isSimpleMode ? "超えた分の半分だけ年金が減る仕組み" : "超過分の半額が厚生年金から減額される",
        badge: "半分カット",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: TrendingDown,
      },
      {
        label: isSimpleMode ? "国民年金（基礎年金）のあつかい" : "老齢基礎年金",
        value: "全額支給",
        unit: "（減額なし）",
        oldValue: "どれだけ給料が高くても満額",
        description: isSimpleMode ? "国民年金は1円も減らされません！" : "カット対象は老齢厚生年金（報酬比例部分のみ）",
        badge: "100%支給",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "制度のこれからの動き" : "制度見直しの議論動向",
        value: "62万円案",
        unit: "や撤廃検討",
        oldValue: "シニアの就労意欲阻害が問題視",
        description: isSimpleMode ? "もっと働きやすくするルール改正を議論中" : "人手不足に対応した基準引上げや廃止の審議",
        badge: "改正審議中",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Clock,
      },
    ],
    "elderly-healthcare-cost": [
      {
        label: isSimpleMode ? "病院の窓口で払う割合" : "一定所得以上の窓口負担割合",
        value: "2割",
        unit: "負担",
        oldValue: "これまで一律1割だった層の一部",
        description: isSimpleMode ? "年金が多い高齢者は2割になりました" : "単身年収200万円以上・複数320万円以上",
        badge: "2割負担導入",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: HeartPulse,
      },
      {
        label: isSimpleMode ? "1割のままの人の割合" : "1割負担を維持する高齢者",
        value: "約 8",
        unit: "割の世帯",
        oldValue: "単身年収200万円未満の一般層",
        description: isSimpleMode ? "ほとんどのおじいちゃんおばあちゃんは1割！" : "後期高齢者全体の約80%は1割負担のまま据置",
        badge: "約80%は1割",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "急激な値上げを抑える特例" : "激変緩和措置（負担上限）",
        value: "終了済",
        unit: "（3年間特例）",
        oldValue: "外来の負担増月3,000円以内措置",
        description: isSimpleMode ? "3年間の緩和期間が終了し本格運用へ" : "制度施行から3年が経過し通常上限へ移行",
        badge: "本格運用へ",
        badgeColor: "bg-slate-100 text-slate-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "現役並みに稼いでいる人" : "現役並み所得者の負担割合",
        value: "3割",
        unit: "負担",
        oldValue: "課税所得145万円以上の層",
        description: isSimpleMode ? "若い人と同じ3割を支払う層" : "単身年収約383万円以上は現役世代と同負担",
        badge: "現役並み3割",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: ShieldCheck,
      },
    ],
    "childcare-leave-benefit": [
      {
        label: isSimpleMode ? "育休中にもらえる手取り割合" : "実質的な手取り給付率",
        value: "100",
        unit: "%（手取り10割）",
        oldValue: "従来の育休手当は手取り約80%",
        description: isSimpleMode ? "休んでもいつもの手取りが減らない！" : "社会保険料免除・非課税により手取り額100%達成",
        badge: "手取り10割",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Baby,
      },
      {
        label: isSimpleMode ? "手当自体の給付率" : "出生後休業支援給付の支給率",
        value: "80",
        unit: "%",
        oldValue: "従来の育休給付金は額面の67%",
        description: isSimpleMode ? "給料の8割が国から振り込まれる！" : "額面賃金の80%を給付（上限額設定あり）",
        badge: "給付率80%",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "もらえる期間の上限" : "新給付の対象期間",
        value: "最大 28",
        unit: "日間",
        oldValue: "産後パパ育休（出生時育児休業）枠",
        description: isSimpleMode ? "産後すぐの約1ヶ月間が対象！" : "出生直後の最も人手が必要な期間を重点支援",
        badge: "最大28日間",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Calendar,
      },
      {
        label: isSimpleMode ? "もらえる条件" : "両親ともに育休の要件",
        value: "父母とも",
        unit: "育休取得",
        oldValue: "片親のみの場合は従来の67%給付",
        description: isSimpleMode ? "パパもママも一緒に休むのが条件！" : "配偶者の育休取得（または片親・自営業特例）",
        badge: "共育て推進",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Users,
      },
    ],
    "rideshare-deregulation": [
      {
        label: isSimpleMode ? "乗るときの料金水準" : "事前確定タクシー同等運賃",
        value: "タクシー同等",
        unit: "（事前確定）",
        oldValue: "アプリで乗る前に料金が確定",
        description: isSimpleMode ? "ぼったくりの心配なしで明朗会計！" : "メーターではなく配車アプリで事前確定・決済",
        badge: "同等運賃",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Car,
      },
      {
        label: isSimpleMode ? "走れる地域と時間" : "運行時間帯・エリアの制限",
        value: "不足時限定",
        unit: "（金曜深夜等）",
        oldValue: "いつでも走れるわけではない",
        description: isSimpleMode ? "タクシーが捕まらない時間・場所で活躍！" : "国交省がデータで認定したタクシー不足枠",
        badge: "条件付き解禁",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "事故や安全の責任" : "運行管理と安全責任の主体",
        value: "タクシー会社",
        unit: "が管理",
        oldValue: "個人の自己責任ではなく会社責任",
        description: isSimpleMode ? "アルコール検査や車両整備もプロが管理！" : "点呼・研修・車両点検・保険をタクシー事業者が担う",
        badge: "安全管理徹底",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "全面解禁の議論" : "ライドシェア新法（全面解禁論）",
        value: "新法制定",
        unit: "を審議中",
        oldValue: "タクシー会社以外が運営する解禁論",
        description: isSimpleMode ? "一般企業や海外アプリの自由解禁は議論中" : "安全確保と地域交通維持を巡る国会審議",
        badge: "法制化議論",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: FileCheck,
      },
    ],
    "high-professional-system": [
      {
        label: isSimpleMode ? "対象になる年収の条件" : "年収要件（平均給与3倍水準）",
        value: "1,075",
        unit: "万円以上",
        oldValue: "法改正時の基準（当面維持）",
        description: isSimpleMode ? "高年収のプロフェッショナルだけが対象！" : "明確に高所得な労働者に限定された制度",
        badge: "年収1,075万円",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Briefcase,
      },
      {
        label: isSimpleMode ? "時間のルール・残業代" : "労働時間規制・割増賃金",
        value: "適用除外",
        unit: "（残業代なし）",
        oldValue: "1日8時間、週40時間、深夜割増除外",
        description: isSimpleMode ? "働く時間ではなく仕事の成果で評価！" : "裁量労働制と異なり労働時間の概念自体を除外",
        badge: "成果主義",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "いやなら断れる権利" : "本人の書面同意・撤回権",
        value: "撤回自由",
        unit: "（いつでも可）",
        oldValue: "会社が無理やり適用することは違法",
        description: isSimpleMode ? "自分の意志でサインし、いつでもやめられる！" : "労使委員会の決議＋本人の自由な同意が必須要件",
        badge: "同意撤回権",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "健康を守るための義務" : "健康管理時間の義務的措置",
        value: "年 104",
        unit: "日以上の休日",
        oldValue: "週40時間超が月100時間で医師面接",
        description: isSimpleMode ? "働きすぎを防ぐ病院チェックが法律で義務！" : "在社時間の把握とインターバル規制等の義務化",
        badge: "医師面接義務",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: HeartPulse,
      },
    ],
    "energy-subsidies": [
      {
        label: isSimpleMode ? "電気代の国からの値引き" : "電気料金の激変緩和補助金",
        value: "最大 4.0",
        unit: "円/kWh",
        oldValue: "猛暑・酷暑乗り切り緊急支援等",
        description: isSimpleMode ? "毎月の電気代が自動的に安くなる！" : "標準世帯で月1,400円前後の直接値引き",
        badge: "自動値引き",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Zap,
      },
      {
        label: isSimpleMode ? "ガス代の国からの値引き" : "都市ガス料金の補助金",
        value: "最大 17.5",
        unit: "円/m³",
        oldValue: "家庭用都市ガス使用量に応じた支援",
        description: isSimpleMode ? "お風呂やキッチンのガス代も補助！" : "月30m³使用の家庭で月約500円の値引き",
        badge: "ガス代軽減",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "面倒な申請手続き" : "補助金の受け取り手続き",
        value: "申請不要",
        unit: "（全自動）",
        oldValue: "電力会社・ガス会社が請求書で減額",
        description: isSimpleMode ? "何もしなくても請求額から引かれます！" : "事業者が国に一括請求し、消費者は請求書で割引",
        badge: "手続きゼロ",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: FileCheck,
      },
      {
        label: isSimpleMode ? "電気代に上乗せされる国民負担" : "再エネ発電促進賦課金",
        value: "約 3.49",
        unit: "円/kWh",
        oldValue: "全国民の電気料金に自動加算",
        description: isSimpleMode ? "自然エネルギーのため全国民で負担中" : "補助金と相殺される形で電気代を押し上げる要因",
        badge: "国民負担金",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
    ],
    "defense-tax-hike": [
      {
        label: isSimpleMode ? "国がめざす防衛費の大きさ" : "防衛関係予算の規模目標",
        value: "GDP比 2",
        unit: "%",
        oldValue: "従来のGDP比1%枠（約5.4兆円）",
        description: isSimpleMode ? "日本の防衛予算を今までの2倍水準へ！" : "年間約8.9兆円規模（5年間で43兆円枠）",
        badge: "GDP比2%目標",
        badgeColor: "bg-slate-100 text-slate-800",
        icon: Shield,
      },
      {
        label: isSimpleMode ? "お給料の税金（所得税）" : "所得税付加税（税率1%）",
        value: "実質据置",
        unit: "（相殺措置）",
        oldValue: "復興特別所得税を1%引下げて相殺",
        description: isSimpleMode ? "毎月の手取り税金は当面増えない工夫！" : "課税期間を延長して防衛財源に付け替え",
        badge: "当面据え置き",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "たばこ1箱あたりの値上がり" : "たばこ税の段階的引き上げ",
        value: "約 60",
        unit: "円/箱",
        oldValue: "1本あたり3円相当の増税",
        description: isSimpleMode ? "たばこを吸う人の負担が増加" : "段階的に1本3円（1箱60円）を引き上げ",
        badge: "段階増税",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "会社の税金（法人税）" : "法人税付加税（4〜4.5%）",
        value: "500万円控除",
        unit: "（中小企業配慮）",
        oldValue: "法人税額から500万円を控除",
        description: isSimpleMode ? "中小企業には負担がかからない仕組み！" : "黒字の大企業を中心に防衛財源を分担",
        badge: "中小企業控除",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Briefcase,
      },
    ],
    "childcare-support-fund": [
      {
        label: isSimpleMode ? "毎月の平均上乗せ" : "平均徴収額（見込み）",
        value: "約450",
        unit: "円/月",
        oldValue: "これまで 0円（負担なし）",
        description: isSimpleMode ? "健保連動で2026年4月から開始" : "医療保険料と合わせて段階的に徴収開始",
        badge: "健保上乗せ",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: HeartPulse,
      },
      {
        label: isSimpleMode ? "集めたお金の使い道" : "子育て支援総枠",
        value: "3.6兆",
        unit: "円/年",
        oldValue: "これまでの支援予算枠",
        description: isSimpleMode ? "手当や給付の財源として全額還元" : "児童手当拡充・育休手取り10割等の恒久財源",
        badge: "全額還元",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: PiggyBank,
      },
      {
        label: isSimpleMode ? "年収600万円の人の負担" : "年収600万世帯（試算）",
        value: "約600",
        unit: "円/月",
        oldValue: "労使折半で会社も半額負担",
        description: isSimpleMode ? "お給料が多い人ほど負担する仕組み" : "収入に応じた拠出額（健康保険組合により差異）",
        badge: "所得比例",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Calculator,
      },
      {
        label: isSimpleMode ? "実質の負担" : "政府試算による実質負担",
        value: "ゼロ",
        unit: "（歳出改革）",
        oldValue: "社会保険料の負担増批判あり",
        description: isSimpleMode ? "社会保障の節約と賃上げで相殺説明" : "社会保障改革等で実質的な追加負担は生じないと説明",
        badge: "歳出改革相殺",
        badgeColor: "bg-slate-100 text-slate-700",
        icon: ShieldCheck,
      },
    ],
    "inheritance-registration": [
      {
        label: isSimpleMode ? "名義変更の期限" : "相続登記の申請期限",
        value: "3年",
        unit: "以内",
        oldValue: "これまで 期限なし（任意）",
        description: isSimpleMode ? "相続を知った日から3年以内に登記！" : "不動産の取得を知った日から3年以内に義務化",
        badge: "義務化施行",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "放置したときのペナルティ" : "過料ペナルティ上限",
        value: "最大10万",
        unit: "円",
        oldValue: "これまで 罰則なし",
        description: isSimpleMode ? "理由なく放っておくと過料の対象に" : "正当な理由のない怠慢に対して裁判所から過料",
        badge: "罰則規定",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "昔に相続した土地" : "過去の放置不動産の猶予",
        value: "2027年3月",
        unit: "まで",
        oldValue: "2024年4月以前の未登記分",
        description: isSimpleMode ? "昔の相続分も3年の間に登記が必要！" : "法改正前の放置分も3年間の猶予期間内に登記要",
        badge: "遡及適用",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Calendar,
      },
      {
        label: isSimpleMode ? "話がまとまらない時の救済" : "相続人申出登記制度",
        value: "単独申出",
        unit: "可能",
        oldValue: "遺産分割が難航すると登記不可だった",
        description: isSimpleMode ? "自分が相続人だと名乗り出れば過料免除！" : "単独で申出登記を行えば10万円の過料を回避可能",
        badge: "過料回避策",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: FileCheck,
      },
    ],
    "myna-drivers-license": [
      {
        label: isSimpleMode ? "免許の更新手数料" : "更新手数料（一体化）",
        value: "2,100",
        unit: "円",
        oldValue: "従来免許証 2,500円（差額400円安）",
        description: isSimpleMode ? "マイナ一体化で更新料が400円お得に！" : "マイナ免許証保有者は更新手数料が優遇",
        badge: "400円お得",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "住所変更の手間" : "引越し時の住所変更",
        value: "1箇所",
        unit: "（ワンストップ）",
        oldValue: "これまで 警察署・交番に別届け出",
        description: isSimpleMode ? "市役所で手続きすれば警察への届出不要！" : "自治体窓口のマイナ更新で警察署変更も同時完了",
        badge: "ワンストップ",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "更新講習の受け方" : "オンライン更新講習",
        value: "24時間",
        unit: "自宅受講可能",
        oldValue: "これまで 免許センター等で対面受講",
        description: isSimpleMode ? "優良運転者はスマホで好きな時に講習！" : "優良・一般運転者はマイナポータルから受講可",
        badge: "スマホ受講",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "持ち方のルール" : "所持形態の選択制",
        value: "3通り",
        unit: "から選択",
        oldValue: "従来型免許証のみ",
        description: isSimpleMode ? "一体化・従来のまま・2枚持ちから自由に選べる" : "義務ではなく任意。従来の運転免許証の継続も可能",
        badge: "任意選択",
        badgeColor: "bg-slate-100 text-slate-700",
        icon: ShieldCheck,
      },
    ],
    "severance-pay-tax": [
      {
        label: isSimpleMode ? "20年目までの非課税枠" : "勤続20年以下（年あたり）",
        value: "年40万",
        unit: "円/年",
        oldValue: "勤続1年ごとに40万円控除",
        description: isSimpleMode ? "20年働くと800万円まで税金ゼロ" : "勤続年数×40万円の非課税枠を付与",
        badge: "現行維持",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "20年超の現行優遇枠" : "勤続20年超（年あたり）",
        value: "年70万",
        unit: "円/年",
        oldValue: "21年目以降は控除枠が急拡大",
        description: isSimpleMode ? "長く勤めるほど税金の割引が大きかった" : "長期勤続優遇として年70万円の控除枠",
        badge: "現行優遇",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Calculator,
      },
      {
        label: isSimpleMode ? "見直し議論の内容" : "一律平準化議論",
        value: "年40万",
        unit: "一律化案",
        oldValue: "20年超の70万円枠",
        description: isSimpleMode ? "転職しやすくするため一律にする案で議論" : "長期優遇を廃止し全勤続年数を一律40万円案で検討",
        badge: "見直し論点",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "退職金の税金ルール" : "退職所得の1/2課税",
        value: "1/2課税",
        unit: "維持方針",
        oldValue: "控除後を半分にして超低税率課税",
        description: isSimpleMode ? "他の給料と別にして安くする仕組みは継続" : "分離課税かつ1/2課税の恩恵は基本的に維持の見通し",
        badge: "低税率継続",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
    ],
    "gasoline-subsidies-trigger": [
      {
        label: isSimpleMode ? "補助金による値引き" : "店頭価格抑制幅",
        value: "約10〜15",
        unit: "円/L抑制",
        oldValue: "全国平均175円/Lを目安に激変緩和",
        description: isSimpleMode ? "ガソリンスタンドの急激な値上がりを抑制" : "元売りへの補助金で給油所販売価格を抑制中",
        badge: "価格抑制",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "使われた税金の総額" : "国費投入累計額",
        value: "約6兆",
        unit: "円以上",
        oldValue: "予備費等を充当して延長を継続",
        description: isSimpleMode ? "国の予備費などから巨額の税金が使われた" : "財政再建や脱炭素の観点から賛否が分かれる規模",
        badge: "巨額財源",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "ガソリンにかかる旧暫定税率" : "当分の間税率（暫定分）",
        value: "25.1",
        unit: "円/L",
        oldValue: "本則税率28.7円＋暫定分25.1円",
        description: isSimpleMode ? "ガソリンには税金にさらに消費税がかかる" : "旧暫定税率が維持され二重課税との批判も根強い",
        badge: "暫定税率",
        badgeColor: "bg-slate-100 text-slate-700",
        icon: Calculator,
      },
      {
        label: isSimpleMode ? "トリガー条項の発動基準" : "トリガー条項基準価格",
        value: "160",
        unit: "円/L（3ヶ月）",
        oldValue: "震災復興財源法により凍結中",
        description: isSimpleMode ? "法律では160円超で減税されるはずが凍結中" : "凍結解除なら25.1円即減税だが流通混乱懸念で維持",
        badge: "凍結継続",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
    ],
    "nursing-care-copay": [
      {
        label: isSimpleMode ? "いま1割負担の人" : "1割負担利用者の割合",
        value: "約90",
        unit: "％が1割",
        oldValue: "単身年収280万円未満等は原則1割",
        description: isSimpleMode ? "大半のおじいちゃん・おばあちゃんは1割" : "現行制度では8割強〜9割弱の利用者が1割負担",
        badge: "大半が1割",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: HeartPulse,
      },
      {
        label: isSimpleMode ? "2割負担の対象拡大案" : "見直し検討対象ライン",
        value: "単身280万未満",
        unit: "への引下げ議論",
        oldValue: "現行は単身280万円以上のみ2割",
        description: isSimpleMode ? "年金が多い人の窓口負担を増やす議論が継続" : "財政審議会等で提起されるも激変緩和で慎重判断",
        badge: "検討継続",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "65歳以上の介護保険料" : "全国平均基準保険料",
        value: "月6,225",
        unit: "円/月",
        oldValue: "制度開始当初（2000年）約2,911円",
        description: isSimpleMode ? "お年寄りが増えて毎月の保険料は右肩上がり" : "第9期計画（2024〜2026年度）で過去最高を更新",
        badge: "過去最高",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Calculator,
      },
      {
        label: isSimpleMode ? "月の支払い上限制度" : "高額介護サービス費上限",
        value: "月44,400",
        unit: "円/月（一般）",
        oldValue: "所得区分に応じた月額上限設定",
        description: isSimpleMode ? "どんなに使っても上限を超えた分は戻る！" : "2割負担になっても高額介護サービス費で上限ガード",
        badge: "上限ストッパー",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: ShieldCheck,
      },
    ],
    "electric-kickboard-rules": [
      {
        label: isSimpleMode ? "運転できる条件" : "運転免許の要否",
        value: "免許不要",
        unit: "（16歳以上）",
        oldValue: "これまで 原付免許が必須だった",
        description: isSimpleMode ? "16歳以上なら免許なしで乗れるように！" : "特定小型原動機付自転車として免許不要化",
        badge: "免許不要",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "走れるスピード" : "最高速度（車道 / 歩道）",
        value: "20km / 6km",
        unit: "最高時速",
        oldValue: "歩道走行は一切不可だった",
        description: isSimpleMode ? "緑ランプ点滅モード（6km/h）なら歩道も可" : "特例特定小型原動機付自転車モードで一部歩道走行可",
        badge: "歩道特例あり",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Car,
      },
      {
        label: isSimpleMode ? "ヘルメットのルール" : "ヘルメット着用義務",
        value: "努力義務",
        unit: "（推奨）",
        oldValue: "これまで 道路交通法で着用義務",
        description: isSimpleMode ? "かぶることがおすすめだけど罰則なし" : "自転車と同様に着用努力義務（着用強く推奨）",
        badge: "努力義務",
        badgeColor: "bg-slate-100 text-slate-700",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "公道を走るためのルール" : "必須装備・保安基準",
        value: "ナンバー＋自賠責",
        unit: "必須",
        oldValue: "一般原付の保安基準",
        description: isSimpleMode ? "緑色の最高速度表示灯と自賠責保険が必須！" : "最高速度表示灯・ナンバープレート・自賠責加入義務",
        badge: "装備必須",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: AlertTriangle,
      },
    ],
    "selective-separate-surnames": [
      {
        label: isSimpleMode ? "選べる名字のルール" : "選択制の仕組み",
        value: "同姓・別姓",
        unit: "どちらも自由",
        oldValue: "民法750条で夫婦どちらかの姓に強制統一",
        description: isSimpleMode ? "同じ名字にしたい人はそのまま、別々も選べる" : "同姓を強制せず、希望するカップルのみ別姓を選択可能",
        badge: "自由選択",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "名義変更の手間" : "改姓手続きのコスト",
        value: "ゼロ",
        unit: "（別姓選択時）",
        oldValue: "免許・銀行口座・パスポート等数十箇所の変更",
        description: isSimpleMode ? "結婚しても名前を変えなければ手続きゼロ！" : "改姓に伴う各種名義変更の手間・費用・キャリア断絶ゼロ",
        badge: "手続きゼロ",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "子どもの名字" : "子どもの姓の決定方法",
        value: "結婚時に決定",
        unit: "（兄弟同姓）",
        oldValue: "両親と同姓",
        description: isSimpleMode ? "結婚するときに子どもの名字をあらかじめ決める" : "法制審議会答申案では婚姻時に子どもの姓を統一決定",
        badge: "事前統一",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Baby,
      },
      {
        label: isSimpleMode ? "経済界・企業の要望" : "経団連の提言",
        value: "早期実現",
        unit: "要望書提出",
        oldValue: "通称使用の拡大で対応",
        description: isSimpleMode ? "会社でもトラブルが多いので早く変えてほしい要望" : "ビジネス上の不都合・海外渡航トラブル解消を経済界が要望",
        badge: "経済界推進",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Briefcase,
      },
    ],
    "school-lunch-free": [
      {
        label: isSimpleMode ? "毎月の給食代" : "公立小中学校給食費（平均）",
        value: "約5,000",
        unit: "円/月・人",
        oldValue: "小学校約4,500円・中学校約5,200円",
        description: isSimpleMode ? "子ども1人あたり年間約5〜6万円の負担" : "保護者が銀行口座振替等で毎月負担",
        badge: "月約5千円",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "2人・3人兄弟の家計" : "年間軽減額（子ども2人）",
        value: "年10〜12万",
        unit: "円の負担減",
        oldValue: "全額保護者の家計負担",
        description: isSimpleMode ? "給食費がタダになると毎月1万円以上浮く！" : "多子世帯ほど直接的な生活防衛・子育て支援効果大",
        badge: "家計直接支援",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "いまタダになっている自治体" : "無償化先行自治体率",
        value: "約30",
        unit: "％が実施",
        oldValue: "財政力のある自治体のみ独自実施",
        description: isSimpleMode ? "住んでいる街によって給食代が違う問題が発生" : "自治体間格差の是正を求め全国一律化を要望",
        badge: "地域格差是正",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "全国でタダにする国の予算" : "全国無償化の所要財源",
        value: "約4,500億",
        unit: "円/年",
        oldValue: "地方自治体の単独持ち出し",
        description: isSimpleMode ? "国のお金で全国いっせいにタダにする議論が進行" : "文部科学省・国会で国費負担の一律無償化を議論中",
        badge: "国費投入議論",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: GraduationCap,
      },
    ],
    "ideco-expansion": [
      {
        label: isSimpleMode ? "加入できる年齢の上限" : "加入可能年齢の上限",
        value: "70歳",
        unit: "まで延長検討",
        oldValue: "2022年法改正で65歳まで拡大済み",
        description: isSimpleMode ? "シニアで働いている間もずっと積み立て可能に" : "高齢期の就労長期化に合わせた非課税枠の拡大議論",
        badge: "70歳まで",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "企業年金がある人の上限" : "DB併図時の拠出限度額",
        value: "月2.0万",
        unit: "円/月に引上げ",
        oldValue: "これまで 月1.2万円の上限だった",
        description: isSimpleMode ? "2024年12月から会社員の上限が月2万円にアップ！" : "企業型年金規約ごとの不公平を解消し一律2万円へ",
        badge: "限度額拡大",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "うれしい税金の割引" : "3重の税制優遇メリット",
        value: "トリプル",
        unit: "節税効果",
        oldValue: "一般預金は利息・受取時に課税",
        description: isSimpleMode ? "積み立て・運用・受け取りの全部で税金が安くなる" : "掛金全額所得控除＋運用益非課税＋受取時退職・年金控除",
        badge: "トリプル節税",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: PiggyBank,
      },
      {
        label: isSimpleMode ? "お金を引き出せないルール" : "原則引出不可ルール",
        value: "60歳まで",
        unit: "ロック",
        oldValue: "老後資金形成目的のため原則中途解約不可",
        description: isSimpleMode ? "急なお金が必要になっても60歳まで出せない" : "資金拘束（流動性リスク）がある点には注意が必要",
        badge: "60歳拘束",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
    ],
    "kodomo-daretemo-tsuen": [
      {
        label: isSimpleMode ? "親のお仕事の条件" : "就労要件の有無",
        value: "就労不要",
        unit: "（専業主婦等も対象）",
        oldValue: "これまで 就労証明書が必須だった",
        description: isSimpleMode ? "働いていなくても誰でも利用可能に！" : "すべての未就園児（0〜2歳児）を対象化",
        badge: "就労要件なし",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "預けられる時間" : "利用可能時間（上限）",
        value: "月 10",
        unit: "時間/人",
        oldValue: "一時預かりの空き枠のみ（予約難）",
        description: isSimpleMode ? "毎月一定時間の枠がもらえる！" : "国が月10時間の利用枠を制度として創設",
        badge: "月10時間枠",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "1時間の利用代金" : "利用者負担額（目安）",
        value: "1時間 約300",
        unit: "円",
        oldValue: "民間一時預かり 1時間1,200円以上",
        description: isSimpleMode ? "公的な安い値段で気軽に使える！" : "低所得世帯・非課税世帯は無償・減免措置あり",
        badge: "公的低料金",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "いつから使える？" : "全国本格施行時期",
        value: "2026年4月",
        unit: "本格スタート",
        oldValue: "2024〜2025年度 試行的事業",
        description: isSimpleMode ? "日本全国の保育園で使えるように！" : "改正子ども・子育て支援法に基づき本格導入",
        badge: "本格施行",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Baby,
      },
    ],
    "high-school-tuition-free": [
      {
        label: isSimpleMode ? "国の給料制限ライン" : "国の所得制限基準",
        value: "年収約910万",
        unit: "円未満が対象",
        oldValue: "公立年11.88万・私立年最大39.6万",
        description: isSimpleMode ? "910万円を超えると国の補助金はゼロ" : "国の就学支援金は年収目安910万円で制限維持",
        badge: "国基準制限あり",
        badgeColor: "bg-slate-100 text-slate-700",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "東京や大阪のルール" : "先行自治体の所得制限",
        value: "完全撤廃",
        unit: "（私立高校も全額）",
        oldValue: "所得制限ありの補助金だった",
        description: isSimpleMode ? "親の年収に関係なく私立高校も全額支援！" : "東京都・大阪府等で私立高校平均授業料を全額助成",
        badge: "都府で全額支援",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "浮く教育費（3年間）" : "3年間の授業料軽減額",
        value: "約35〜140万",
        unit: "円の学費減",
        oldValue: "全額保護者の家計負担だった",
        description: isSimpleMode ? "公立約35万円・私立最大約140万円浮く！" : "高校年代の最も重い固定教育費を大幅カット",
        badge: "教育費大幅減",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "住む場所の格差" : "地域間格差の課題",
        value: "地域差拡大",
        unit: "全国一律化協議",
        oldValue: "公立無償のみ全国一律だった",
        description: isSimpleMode ? "住む街による不公平をなくす議論が進行中" : "大都市と地方の教育格差是正へ国費負担を議論",
        badge: "全国一律化協議",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: GraduationCap,
      },
    ],
    "pension-contribution-45years": [
      {
        label: isSimpleMode ? "保険料を払う期間" : "保険料納付期間の延長",
        value: "65歳まで",
        unit: "（45年間へ）",
        oldValue: "これまで 20歳〜60歳（40年間）",
        description: isSimpleMode ? "納付が5年間延長される改革案が議論中" : "次期年金改革で40年から45年への延長を審議",
        badge: "5年延長案",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "自営業の追加の支払い" : "第1号被保険者の追加負担",
        value: "約102万",
        unit: "円（5年合計）",
        oldValue: "60歳以降は任意加入のみだった",
        description: isSimpleMode ? "自営業や無職の人は約100万円多く払う" : "月約1.7万円×60ヶ月を全額自己負担納付",
        badge: "第1号約100万追加",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "将来もらえる年金（満額）" : "将来の基礎年金（年額）",
        value: "年約92万",
        unit: "円/年（＋10.2万）",
        oldValue: "現行40年満額 年約81.6万円",
        description: isSimpleMode ? "将来もらえる年金が月約8,500円増える！" : "受給額が約1割強底上げされ高齢期貧困を防止",
        badge: "年金額1割増",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: TrendingUp,
      },
      {
        label: isSimpleMode ? "元が取れる年齢" : "損益分岐点（年数）",
        value: "約75歳",
        unit: "（受給約10年）",
        oldValue: "平均寿命まで生きればプラス",
        description: isSimpleMode ? "受給開始から10年生きれば確実にプラス！" : "平均寿命（81〜87歳）まで生きれば支払額以上を回収",
        badge: "75歳で元取れ",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: ShieldCheck,
      },
    ],
    "abandoned-house-tax-hike": [
      {
        label: isSimpleMode ? "新しくできた警告区分" : "新設された指定区分",
        value: "管理不全空家",
        unit: "（早期指導）",
        oldValue: "倒壊寸前の「特定空家」のみだった",
        description: isSimpleMode ? "窓割れ・草ぼうぼうの段階で警告される！" : "放置すれば危険になる前の段階で自治体が勧告",
        badge: "早期指導新設",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "警告された後の税金" : "固定資産税の増税倍率",
        value: "実質最大6倍",
        unit: "（住宅特例解除）",
        oldValue: "住宅用地特例で1/6減額が続いていた",
        description: isSimpleMode ? "勧告を受けると税金の割引が即座に消滅！" : "小規模住宅用地の課税標準1/6特例が取り消し",
        badge: "実質最大6倍",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "家を壊す費用の相場" : "解体工事費の相場",
        value: "約150〜250万",
        unit: "円（木造家屋）",
        oldValue: "放置した方が税金が安かった",
        description: isSimpleMode ? "自治体の解体補助金（最大数十万円）を活用" : "放置増税を払い続けるより更地化・売却が有利に",
        badge: "解体費用の壁",
        badgeColor: "bg-slate-100 text-slate-700",
        icon: Home,
      },
      {
        label: isSimpleMode ? "日本の空き家の数" : "全国の空き家総数",
        value: "約900万",
        unit: "戸（過去最高）",
        oldValue: "年々増加して社会問題化",
        description: isSimpleMode ? "全国で過去最多。国が対策を本気で強化中" : "所有者不明土地法や空家特措法で活用を促進",
        badge: "過去最高",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: TrendingUp,
      },
    ],
    "accommodation-tax-tourism": [
      {
        label: isSimpleMode ? "1泊あたりの税金" : "宿泊税額の目安",
        value: "100〜2,000円超",
        unit: "1人1泊あたり",
        oldValue: "東京100〜200円等",
        description: isSimpleMode ? "ホテルのグレードや街によって金額が変わる" : "京都市最高1,000円、ニセコ町最高2,000円など",
        badge: "1泊100〜2,000円",
        badgeColor: "bg-sky-100 text-sky-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "導入している街の数" : "導入・検討自治体数",
        value: "全国30以上",
        unit: "の自治体",
        oldValue: "東京、大阪、京都など一部都市のみ",
        description: isSimpleMode ? "全国の人気観光地で導入がどんどん拡大中！" : "北海道、福岡、金沢、長崎など全国に波及",
        badge: "全国30自治体超",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: MapPin,
      },
      {
        label: isSimpleMode ? "集めたお金の使い道" : "税金の主な使途",
        value: "混雑・ゴミ対策",
        unit: "（観光公害防止）",
        oldValue: "観光客を呼ぶプロモーション中心だった",
        description: isSimpleMode ? "観光バスを増やしたりきれいなトイレを作る！" : "観光特急バス増便・多言語標識・美化清掃に充当",
        badge: "オーバーツーリズム対策",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "だれが払う？" : "課税対象と二重価格議論",
        value: "内外二重価格",
        unit: "の議論台頭",
        oldValue: "外国人も日本人も一律課税",
        description: isSimpleMode ? "日本の出張サラリーマンの免除などが議論中" : "外国人富裕層と国内ビジネス客の区分議論が浮上",
        badge: "二重価格議論",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Users,
      },
    ],
    "forest-environment-tax": [
      {
        label: isSimpleMode ? "1人あたりの税金" : "年間税額（国税）",
        value: "年 1,000",
        unit: "円/人",
        oldValue: "復興特別住民税（年1,000円）終了",
        description: isSimpleMode ? "住民税と一緒に毎年1,000円が引かれる" : "個人住民税均等割に恒久的に上乗せ徴収",
        badge: "年1,000円上乗せ",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "税金を払う人の数" : "全国の納税義務者数",
        value: "約6,000万",
        unit: "人（住民税納税者）",
        oldValue: "地方独自の間伐税等のみだった",
        description: isSimpleMode ? "日本で働くほぼすべての人が対象" : "全国一律国税として約600億円の財源を確保",
        badge: "約6,000万人",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "自治体へのお金の配り方" : "配分基準（譲与税）",
        value: "面積5割・人口3割",
        unit: "（林業就業者2割）",
        oldValue: "省庁の補助金採択方式だった",
        description: isSimpleMode ? "森林の広さだけでなく人口の多さでも配分" : "森林環境譲与税として全国市区町村へ交付",
        badge: "配分基準",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Trees,
      },
      {
        label: isSimpleMode ? "使われていないお金" : "都市部の基金積立問題",
        value: "数百億円",
        unit: "が基金に眠る",
        oldValue: "配分なし",
        description: isSimpleMode ? "山がない大都会でお金が余って貯金されている" : "大都市自治体での使途不足と配分基準見直し議論",
        badge: "基金積立問題",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: AlertTriangle,
      },
    ],
    "customer-harassment-prevention": [
      {
        label: isSimpleMode ? "迷惑なお客さんの行為" : "カスハラの行為類型",
        value: "著しい迷惑行為",
        unit: "（明文化）",
        oldValue: "「お客様は神様」で我慢させられていた",
        description: isSimpleMode ? "土下座強要・暴言・SNS晒しは明確にダメ！" : "強要罪・業務妨害罪に抵触する行為を定義化",
        badge: "行為の明文化",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Ban,
      },
      {
        label: isSimpleMode ? "守るためのルール" : "条例・法制化の動向",
        value: "企業の防止義務",
        unit: "（全国拡大）",
        oldValue: "企業の自主対応マニュアル止まり",
        description: isSimpleMode ? "東京都が条例施行、国も全国義務化を審議中" : "パワハラ防止法に準じ従業員保護措置を義務付け",
        badge: "防止義務化へ",
        badgeColor: "bg-slate-100 text-slate-700",
        icon: ShieldAlert,
      },
      {
        label: isSimpleMode ? "店員さんの名札" : "名札の実名表記見直し",
        value: "名字・番号化",
        unit: "（推奨）",
        oldValue: "フルネーム実名表示が当たり前だった",
        description: isSimpleMode ? "ネットに名前や顔を晒されるのを防ぐ！" : "名字のみやイニシャル・スタッフ番号表示を推進",
        badge: "プライバシー保護",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "お店の対応ルール" : "組織対応の徹底",
        value: "複数人＋録音",
        unit: "（警察通報）",
        oldValue: "担当者が1人で謝らされていた",
        description: isSimpleMode ? "1人で謝らせず、上司が同席して通話も録音！" : "現場スタッフを孤立させない組織防衛を義務付け",
        badge: "組織対応義務",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Users,
      },
    ],
    "reskilling-education-benefit": [
      {
        label: isSimpleMode ? "国からのキャッシュバック" : "最大給付率（ハローワーク）",
        value: "最大 80",
        unit: "％支給",
        oldValue: "従来 最大70%（受講中50%＋修了20%）",
        description: isSimpleMode ? "学費の最大80%が戻ってくる神制度！" : "資格取得＋賃金5%アップ要件達成で80%へ拡充",
        badge: "最大80%拡充",
        badgeColor: "bg-violet-100 text-violet-800",
        icon: TrendingUp,
      },
      {
        label: isSimpleMode ? "1年にもらえる上限" : "年間給付上限額",
        value: "年最大 64",
        unit: "万円（3年192万）",
        oldValue: "従来 年最大56万円（3年168万円）",
        description: isSimpleMode ? "高額なITスクールの学費もほぼカバー！" : "専門実践教育訓練で年間上限が引き上げ",
        badge: "年最大64万円",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "勉強中の生活費サポート" : "教育訓練休暇給付金",
        value: "休業給付新設",
        unit: "（生活費補助）",
        oldValue: "退職して失業保険をもらうしかなかった",
        description: isSimpleMode ? "仕事を辞めなくても給付金をもらって休める" : "会社を休業して本格的に学び直す間の生活費を補助",
        badge: "休業給付新設",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: BookOpen,
      },
      {
        label: isSimpleMode ? "どんな講座が学べる？" : "対象講座の重点分野",
        value: "AI・DX講座",
        unit: "大幅拡充",
        oldValue: "簿記や宅建などの伝統的資格中心だった",
        description: isSimpleMode ? "AI・データサイエンス・プログラミングが充実！" : "人手不足の成長産業へ向けた講座が多数指定",
        badge: "AI・DX重点",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Sparkles,
      },
    ],
    "hay-fever-countermeasures": [
      {
        label: isSimpleMode ? "スギの木を切るスピード" : "スギ人工林伐採ペース",
        value: "年 7万",
        unit: "haへ加速（4割増）",
        oldValue: "年間約5万ヘクタールのペースだった",
        description: isSimpleMode ? "国が本気でスギの木を切り倒して減らす！" : "30年で花粉発生量を半減させる10年計画推進中",
        badge: "伐採4割加速",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Trees,
      },
      {
        label: isSimpleMode ? "新しく植える木" : "少花粉スギ苗木の割合",
        value: "9割超",
        unit: "へ引き上げ",
        oldValue: "通常のスギ苗木が多く植えられていた",
        description: isSimpleMode ? "切った後は花粉が出ない木に植え替える！" : "花粉の少ない優良品種への転換を強力推進",
        badge: "少花粉苗木9割",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "アレルギーを根本から治す薬" : "舌下免疫療法（SLIT）薬",
        value: "供給量倍増",
        unit: "（約8割改善）",
        oldValue: "薬が品薄で治療を始めにくかった",
        description: isSimpleMode ? "保険適用で治療薬が増産され始めやすくなった" : "3年間の服薬で約8割の患者で症状が消失・軽減",
        badge: "根本治療薬倍増",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: HeartPulse,
      },
      {
        label: isSimpleMode ? "社会の経済的な損" : "経済損失の奪還効果",
        value: "年数千億円",
        unit: "の損失防止",
        oldValue: "春の集中力低下・医療費で大打撃",
        description: isSimpleMode ? "春に仕事や勉強が手につかない損を取り戻す！" : "労働生産性の改善と医療費抑制による国家効果",
        badge: "経済損失防止",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: TrendingDown,
      },
    ],
    "income-barrier-career-up": [
      {
        label: isSimpleMode ? "会社がもらえる国の補助金" : "キャリアアップ助成金",
        value: "最大 50",
        unit: "万円/人支給",
        oldValue: "手取り補填に対する国の補助なし",
        description: isSimpleMode ? "パートの手取りを減らさない会社にお金が出る！" : "社会保険適用時処遇改善コースで最長2年支援",
        badge: "1人最大50万円",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "パートさんの手取り" : "手取り補填（手当支給）",
        value: "全額補填",
        unit: "（手取り減ゼロ）",
        oldValue: "106万で社保天引きされ手取り約15%急減",
        description: isSimpleMode ? "会社から手当が出て手取りが減らない！" : "社会保険適用促進手当により「手取りの崖」解消",
        badge: "手取り減ゼロ",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "将来もらえる年金" : "厚生年金加入メリット",
        value: "年金増額",
        unit: "（将来の受取プラス）",
        oldValue: "国民年金（第3号）のみで受給が少なかった",
        description: isSimpleMode ? "手取りは減らずに将来もらえる年金が増える！" : "手取り維持のまま厚生年金と傷病手当金の権利獲得",
        badge: "将来年金アップ",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: TrendingUp,
      },
      {
        label: isSimpleMode ? "いつまで続く？" : "支援措置の適用期間",
        value: "最長 2年間",
        unit: "（時限措置）",
        oldValue: "なし",
        description: isSimpleMode ? "2年の間に時給を上げたり働く時間を増やす！" : "抜本的な年金制度改革までの暫定激変緩和パッケージ",
        badge: "最長2年の時限措置",
        badgeColor: "bg-amber-100 text-amber-900",
        icon: Clock,
      },
    ],

    "financial-income-tax": [
      {
        label: isSimpleMode ? "お金持ちの株の税率" : "金融所得の新税率検討",
        value: "25〜30",
        unit: "%",
        oldValue: "これまで一律 20.315%",
        description: isSimpleMode ? "大金持ちの株の税金を高くする！" : "「1億円の壁」打破に向け段階引き上げ論議",
        badge: "最大30%案",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: TrendingUp,
      },
      {
        label: isSimpleMode ? "ふつうの人の新NISA" : "一般投資家のNISA口座",
        value: "完全非課税",
        unit: "維持",
        oldValue: "現行のまま非課税枠1,800万円堅持",
        description: isSimpleMode ? "一般の人のNISAは増税されない！" : "庶民の資産形成枠は増税対象外を明記",
        badge: "非課税を死守",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "国に入る税金" : "想定増税税収",
        value: "数千億円",
        unit: "規模 / 年",
        oldValue: "金融所得の分離課税で税収伸び悩み",
        description: isSimpleMode ? "お金持ちから集めて子育て等に使う！" : "富の再分配と社会保障・少子化対策財源へ",
        badge: "再分配の強化",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "株価への影響は？" : "市場冷え込みリスク",
        value: "投資意欲減退",
        unit: "懸念",
        oldValue: "国内外マネーの逃避リスク",
        description: isSimpleMode ? "株が売られて株価が下がる心配も！" : "「貯蓄から投資へ」に冷や水を浴びせる反対論",
        badge: "市場動向に警戒",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
    ],
    "ev-distance-tax": [
      {
        label: isSimpleMode ? "走った分だけ取られる税金" : "想定走行距離課税額",
        value: "約 3〜5",
        unit: "円 / km",
        oldValue: "EVはガソリン税（約53.8円/L）ゼロ",
        description: isSimpleMode ? "1キロ走るごとに数円の税金を検討！" : "EV普及による燃料税収減の穴埋め新税",
        badge: "1km数円案",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Car,
      },
      {
        label: isSimpleMode ? "年1万km走る人の負担" : "年間想定新税額",
        value: "約 3〜5",
        unit: "万円 / 年",
        oldValue: "ガソリン車は年間約3.6万円の燃料税",
        description: isSimpleMode ? "年1万キロで数万円の新税負担！" : "ガソリン税廃止または並行課税の設計論",
        badge: "年間数万円負担",
        badgeColor: "bg-amber-100 text-amber-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "地方の負担は？" : "地方住民の走行距離",
        value: "都市部の 2倍超",
        unit: "（地方集中）",
        oldValue: "公共交通がなく車が必須の地方",
        description: isSimpleMode ? "田舎ほど税負担が重くなる！" : "生活必需の地方住民に対する実質的増税批判",
        badge: "地方格差の懸念",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "どうやって測る？" : "走行距離の把握技術",
        value: "車検メーター",
        unit: "またはGPS",
        oldValue: "給油メーターのみで把握",
        description: isSimpleMode ? "走った距離を機械やGPSで確認！" : "車載通信器による位置情報追跡とプライバシー課題",
        badge: "プライバシー論争",
        badgeColor: "bg-purple-100 text-purple-800",
        icon: ShieldCheck,
      },
    ],
    "digital-salary-payment": [
      {
        label: isSimpleMode ? "アプリに入れられる上限" : "残高保有上限額",
        value: "最大 100",
        unit: "万円",
        oldValue: "銀行口座のみ（ペイオフ1,000万円）",
        description: isSimpleMode ? "アプリには100万円までしか入らない！" : "超過分は連携する指定銀行口座へ自動出金",
        badge: "上限100万円",
        badgeColor: "bg-purple-100 text-purple-800",
        icon: Smartphone,
      },
      {
        label: isSimpleMode ? "勝手に決められる？" : "労働者の同意",
        value: "完全自由意志",
        unit: "（強制禁止）",
        oldValue: "現金払いまたは本人口座振込",
        description: isSimpleMode ? "会社が強制するのは法律違反！" : "希望する社員のみ書面・電磁的同意で選択",
        badge: "強制は違法",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "アプリがつぶれたら？" : "破綻時保証",
        value: "全額弁済",
        unit: "（数日以内）",
        oldValue: "預金保険制度（1,000万円まで保護）",
        description: isSimpleMode ? "会社が倒産しても国が全額守る！" : "指定保証機関により迅速に全額返金担保",
        badge: "セーフティネット",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: CreditCard,
      },
      {
        label: isSimpleMode ? "ATMでお金をおろせる？" : "現金引出し手数料",
        value: "月1回 無料",
        unit: "（法令義務）",
        oldValue: "所定のATM出金手数料が発生",
        description: isSimpleMode ? "月に1回はタダで現金をおろせる！" : "資金移動業者の指定要件として月1回無料出金を義務付け",
        badge: "月1回無料",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Wallet,
      },
    ],
    "dismissal-monetary-resolution": [
      {
        label: isSimpleMode ? "解決金の目安" : "想定補償水準",
        value: "給与 3〜18",
        unit: "ヶ月分相当",
        oldValue: "職場復帰判決（実態は自主退職多発）",
        description: isSimpleMode ? "お給料の数ヶ月〜1年半分をもらって合意！" : "勤続年数・年齢に応じた標準補償レンジを法定化",
        badge: "月給3〜18ヶ月",
        badgeColor: "bg-amber-100 text-amber-800",
        icon: Scale,
      },
      {
        label: isSimpleMode ? "裁判で勝っても復帰できる？" : "職場復帰困難率",
        value: "約 90",
        unit: "%",
        oldValue: "地位確認判決が出ても元の職場に居場所なし",
        description: isSimpleMode ? "勝っても9割の人が結局辞めている現実！" : "泥沼の労使対立を金銭で迅速救済する立法趣旨",
        badge: "現実的救済",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Briefcase,
      },
      {
        label: isSimpleMode ? "誰が請求できる？" : "制度の申立主体",
        value: "労働者側",
        unit: "（使用者申立は激論）",
        oldValue: "明確な法制ルールなし",
        description: isSimpleMode ? "働く側から『お金で解決して』と言える！" : "「企業からのお金でクビ」は首切り自由化と反発大",
        badge: "労働者申立型が先行",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "次の仕事への支援" : "リスキリング連動",
        value: "再就職支援",
        unit: "セット化",
        oldValue: "失業手当のみの受給",
        description: isSimpleMode ? "お金と学び直しで次の成長企業へ！" : "退職金＋公的教育訓練給付金でスムーズな労働移動",
        badge: "セーフティネット",
        badgeColor: "bg-purple-100 text-purple-800",
        icon: Sparkles,
      },
    ],
    "teacher-special-measure-act": [
      {
        label: isSimpleMode ? "先生のお給料上乗せ" : "教職調整額の引き上げ",
        value: "4% → 10%超",
        unit: "（基本給比）",
        oldValue: "1971年以来50年以上「4%」で固定",
        description: isSimpleMode ? "基本給の4%だった手当が10%以上に！" : "残業代ゼロの代わりに支給される調整額の抜本改定",
        badge: "53年ぶり引き上げ",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: GraduationCap,
      },
      {
        label: isSimpleMode ? "先生の年収アップ額" : "年間給与増額目安",
        value: "約 40〜60",
        unit: "万円 / 年",
        oldValue: "時間外手当（残業代）は一切出ず",
        description: isSimpleMode ? "年収が平均50万円ほど底上げ！" : "ボーナス（期末勤勉手当）にも反映され大幅昇給",
        badge: "年40万〜60万増",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: TrendingUp,
      },
      {
        label: isSimpleMode ? "過労死ラインの先生" : "月80時間超残業の割合",
        value: "中学の 約6割",
        unit: "（深刻な過重労働）",
        oldValue: "土日の部活動や行事で際限なく残業",
        description: isSimpleMode ? "先生の残業を減らさないと倒れてしまう！" : "「定額働かせ放題」温存批判と部活地域移行の急務",
        badge: "業務削減が命題",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "先生になりたい人" : "採用倍率の改善目標",
        value: "3倍以上",
        unit: "回復目標",
        oldValue: "一部自治体で1倍台・なり手不足崩壊寸前",
        description: isSimpleMode ? "お給料を上げて若い先生を増やす！" : "質の高い教師確保に向けた待遇と職場環境の再生",
        badge: "志望者回復へ",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Users,
      },
    ],
    "high-cost-medical-cap": [
      {
        label: isSimpleMode ? "中間層の病院代月上限" : "高額療養費（一般区分）",
        value: "約 8〜9",
        unit: "万円 / 月",
        oldValue: "約80,100円 ＋ 1%上乗せ",
        description: isSimpleMode ? "毎月の病院代の上限が少し上がる検討！" : "年収約370万〜770万円世帯の月額上限見直し",
        badge: "月数千円〜1万円増",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: HeartPulse,
      },
      {
        label: isSimpleMode ? "年間国民医療費" : "医療保険の給付総額",
        value: "47兆円超",
        unit: "（過去最高更新）",
        oldValue: "超高額な新薬や高齢化で年1兆円ペース急増",
        description: isSimpleMode ? "国の医療費がパンクしそうになっている！" : "現役世代の保険料高騰を抑えるためのやむなき改革",
        badge: "過去最大規模",
        badgeColor: "bg-amber-100 text-amber-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "4ヶ月目以降の割引" : "多数回該当の据え置き",
        value: "44,400",
        unit: "円 / 月",
        oldValue: "1年間に4回以上該当した場合の定額減額",
        description: isSimpleMode ? "長く治療する人の上限は安く保たれる！" : "抗がん剤・人工透析など長期難病患者のセーフティネット",
        badge: "長期患者を保護",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "高所得者の負担" : "富裕層の上限区分",
        value: "最大 30万円超",
        unit: "（応分負担強化）",
        oldValue: "現行上限は約25.2万円 / 月",
        description: isSimpleMode ? "お金持ちの人ほど病院代を多く払う！" : "負担能力に応じた細分化で財政健全化を図る",
        badge: "富裕層の応分負担",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Wallet,
      },
    ],
    "bicycle-blue-ticket": [
      {
        label: isSimpleMode ? "ながらスマホの反則金" : "携帯電話使用の青切符",
        value: "約 12,000",
        unit: "円",
        oldValue: "口頭指導または即刑事罰（赤切符）",
        description: isSimpleMode ? "スマホを見ながら運転すると1万円超の罰金！" : "画面注視・通話への厳格な青切符適用",
        badge: "重点取締り項目",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "何歳から対象？" : "青切符の適用年齢",
        value: "16歳",
        unit: "以上（高校生含む）",
        oldValue: "刑事責任年齢（14歳以上）",
        description: isSimpleMode ? "高校生も青切符でお金を取られる！" : "原付免許取得可能年齢に合わせて16歳以上を一律対象化",
        badge: "16歳以上対象",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "反則金の相場" : "主な違反の反則金額",
        value: "5,000〜1.2万",
        unit: "円",
        oldValue: "信号無視や逆走もほとんどお咎めなし",
        description: isSimpleMode ? "信号無視や逆走は5,000円〜6,000円！" : "約110種類の危険違反行為に自動車並みの反則金",
        badge: "反則金一律基準",
        badgeColor: "bg-amber-100 text-amber-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "前科はつく？" : "青切符と前科",
        value: "前科なし",
        unit: "（期日内納付時）",
        oldValue: "赤切符は送検・起訴で前科リスク",
        description: isSimpleMode ? "期限内にお金を払えば前科はつかない！" : "反則金を無視し続けると通常の刑事裁判へ移行",
        badge: "行政処分で解決",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
    ],
    "doctor-overtime-regulation": [
      {
        label: isSimpleMode ? "お医者さんの残業上限" : "一般病院の年残業上限（A水準）",
        value: "年 960",
        unit: "時間（月100h未満）",
        oldValue: "事実上の青天井（年2,000時間超も横行）",
        description: isSimpleMode ? "普通の病院の先生は年960時間までに制限！" : "過労死ラインを大幅に引き下げる強制力のある罰則付き上限",
        badge: "年960時間制限",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "当直あけの休み時間" : "勤務間インターバル",
        value: "9〜11",
        unit: "時間の休息義務",
        oldValue: "当直明けにそのまま昼間の手術を執刀",
        description: isSimpleMode ? "当直で徹夜した先生に必ず休みをあげる！" : "連続勤務時間制限（原則28時間）と睡眠確保を義務付け",
        badge: "当直明け休息義務",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: HeartPulse,
      },
      {
        label: isSimpleMode ? "救急病院の特例" : "地域医療特例（B水準）",
        value: "年 1,860",
        unit: "時間上限（縮小中）",
        oldValue: "特例なしの無制限労働",
        description: isSimpleMode ? "救急病院はまだ忙しいが2035年までに減らす！" : "地域救急や産科・小児科を維持するための暫定水準",
        badge: "2035年度廃止目標",
        badgeColor: "bg-amber-100 text-amber-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "看護師さんへのバトンタッチ" : "タスクシフト・シェア",
        value: "特定看護師",
        unit: "などへ業務移管",
        oldValue: "採血や書類作成も医師が一人で抱え込み",
        description: isSimpleMode ? "お医者さんしかできないことだけに集中する！" : "クラーク配置やチーム医療で医師の負担を3割削減",
        badge: "チーム医療の推進",
        badgeColor: "bg-purple-100 text-purple-800",
        icon: Users,
      },
    ],
    "foreign-training-employment": [
      {
        label: isSimpleMode ? "前の会社から転職できる？" : "本人意向による転籍要件",
        value: "1〜2年超",
        unit: "就労＋日本語力",
        oldValue: "原則禁止（パワハラでも転職できず失踪）",
        description: isSimpleMode ? "1〜2年働いて日本語ができれば転職できる！" : "同一業務区分内での条件付き転職を法的に解禁",
        badge: "転職の自由解禁",
        badgeColor: "bg-indigo-100 text-indigo-800",
        icon: Briefcase,
      },
      {
        label: isSimpleMode ? "次のステップ" : "特定技能1号への移行期間",
        value: "3年間",
        unit: "の育成修了で移行",
        oldValue: "技能実習は最長5年で原則母国へ帰国",
        description: isSimpleMode ? "3年真面目に働けばもっと長く日本で働ける！" : "育成期間を経て即戦力枠へ無試験または円滑移行",
        badge: "特定技能へ直結",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: GraduationCap,
      },
      {
        label: isSimpleMode ? "ずっと日本に住める？" : "特定技能2号（永住可能）",
        value: "家族帯同可",
        unit: "・在留更新無制限",
        oldValue: "家族の連れ添いは一切認められず",
        description: isSimpleMode ? "試験に受かれば家族と一緒にずっと暮らせる！" : "高度熟練者への家族帯同と無期限在留の道筋を明示",
        badge: "永住・家族帯同へ",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "地方の心配ごと" : "都市部への人材流出懸念",
        value: "地方から東京へ",
        unit: "流出リスク",
        oldValue: "地方に固定化（移動不可）",
        description: isSimpleMode ? "地方でお金をかけて育てた人が都会に逃げる？" : "受入れ初期費用を負担した地方企業・農家の悲鳴",
        badge: "地方保護が課題",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
    ],
    "paternity-leave-at-birth": [
      {
        label: isSimpleMode ? "パパ育休中の手取り" : "実質手取り補償水準",
        value: "実質 10割",
        unit: "（100%相当）",
        oldValue: "給付金67%（手取り実質8割止まり）",
        description: isSimpleMode ? "休んでもいつものお給料とほぼ同じ額がもらえる！" : "出生後休業支援給付金＋社保全額免除で手取り100%",
        badge: "手取り10割化",
        badgeColor: "bg-pink-100 text-pink-800",
        icon: Baby,
      },
      {
        label: isSimpleMode ? "休める期間" : "産後パパ育休の取得枠",
        value: "産後8週内に",
        unit: "最大 4週間",
        oldValue: "通常の育休のみ（1ヶ月前申請・分割不可）",
        description: isSimpleMode ? "赤ちゃんが生まれてすぐ2回に分けて休める！" : "2回分割取得可能・2週間前申請で柔軟取得",
        badge: "最大4週間・2分割",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Calendar,
      },
      {
        label: isSimpleMode ? "男性の育休取得率" : "民間企業の男性取得率",
        value: "30% 超",
        unit: "へ急上昇中",
        oldValue: "わずか数％台で「男は休めない」時代",
        description: isSimpleMode ? "男性が育休を取るのが当たり前の社会へ！" : "政府目標50%に向けて法改正と公表義務化が牽引",
        badge: "取得率過去最高",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: Users,
      },
      {
        label: isSimpleMode ? "会社の公表義務" : "育休取得率の公表対象",
        value: "100人超",
        unit: "の全企業に拡大",
        oldValue: "従業員1,000人超の大企業のみ義務",
        description: isSimpleMode ? "中小企業もパパが育休を取ったか公表する！" : "企業の採用力・ESG評価に直結し意識改革が定着",
        badge: "100人超へ拡大",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: ShieldCheck,
      },
    ],
    "solar-panel-mandate": [
      {
        label: isSimpleMode ? "新築住宅の設置割合" : "ハウスメーカーの義務基準",
        value: "原則 85",
        unit: "%以上",
        oldValue: "個人の自由（設置率わずか2〜3割）",
        description: isSimpleMode ? "新築の一戸建てはほぼ標準でパネルが載る！" : "大手住宅メーカーへの年間供給目標義務付け",
        badge: "原則標準装備化",
        badgeColor: "bg-amber-100 text-amber-800",
        icon: Sun,
      },
      {
        label: isSimpleMode ? "元が取れるまでの年数" : "初期費用回収年数",
        value: "約 6〜8",
        unit: "年で回収",
        oldValue: "補助金なしで10〜15年以上かかっていた",
        description: isSimpleMode ? "都の補助金と電気代節約で6〜8年で元が取れる！" : "高騰する電気代の自家消費＋売電で早期回収可能",
        badge: "約6〜8年で回収",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: TrendingDown,
      },
      {
        label: isSimpleMode ? "家を建てる初期費用" : "建築時の上乗せ価格",
        value: "約 100〜150",
        unit: "万円上乗せ",
        oldValue: "初期費用ゼロ",
        description: isSimpleMode ? "マイホームを買う費用が100万円以上高くなる！" : "建築費高騰の中で子育て世代の住宅購入負担を圧迫",
        badge: "初期負担増",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Home,
      },
      {
        label: isSimpleMode ? "停電のとき使える？" : "災害時の自立発電",
        value: "1,500",
        unit: "Wまで使用可",
        oldValue: "停電時は家庭内の電気がすべてストップ",
        description: isSimpleMode ? "昼間の停電でも冷蔵庫やスマホが動かせる！" : "自立運転コンセントにより災害在宅避難を強力支援",
        badge: "停電時も安心",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Zap,
      },
    ],
    "otc-similar-drug-restriction": [
      {
        label: isSimpleMode ? "薬局で買える薬の病院代" : "湿布・保湿剤の自己負担",
        value: "選定療養",
        unit: "（差額自腹化）",
        oldValue: "一律3割負担（数百円で入手可能）",
        description: isSimpleMode ? "ドラッグストアで買える薬は自己負担が増える！" : "市販薬との価格差を患者が支払う見直し論議",
        badge: "自己負担増の検討",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: HeartPulse,
      },
      {
        label: isSimpleMode ? "国が削れる医療費" : "想定公費削減効果",
        value: "数千億円",
        unit: "規模 / 年",
        oldValue: "美容目的や大量処方で公費が浪費",
        description: isSimpleMode ? "ムダな薬代を減らして本当に重い病気に使う！" : "財政制度等審議会が提言するセルフメディケーション促進",
        badge: "公費ムダ削減",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Wallet,
      },
      {
        label: isSimpleMode ? "1回にもらえる湿布の枚数" : "処方枚数の制限上限",
        value: "最大 63",
        unit: "枚まで（削減傾向）",
        oldValue: "過去70枚・制限なし時代は大量廃棄",
        description: isSimpleMode ? "一度にたくさん湿布をもらうことはできない！" : "重複処方や残薬防止のための厳格な数量規制",
        badge: "まとめ処方制限",
        badgeColor: "bg-amber-100 text-amber-800",
        icon: AlertTriangle,
      },
      {
        label: isSimpleMode ? "本当に重い病気の人は？" : "難病・アトピー患者の特例",
        value: "3割負担",
        unit: "を維持（例外）",
        oldValue: "全患者一律負担",
        description: isSimpleMode ? "ひどい皮膚病や難病の人は今まで通り安く買える！" : "慢性重症患者の治療継続を守る医療的セーフティネット",
        badge: "重症者は保護",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: ShieldCheck,
      },
    ],
    "stealth-marketing-regulation": [
      {
        label: isSimpleMode ? "ステマをやった会社の罰則" : "措置命令とペナルティ",
        value: "社名公表",
        unit: "（社会的制裁）",
        oldValue: "業界の自主ルールのみで処分なし",
        description: isSimpleMode ? "ヤラセ宣伝をした会社名がニュースで晒される！" : "消費者庁による措置命令と違反事実の全国公表",
        badge: "社名公表の厳罰",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: Ban,
      },
      {
        label: isSimpleMode ? "広告と書く義務" : "表示の明瞭基準",
        value: "#PR #広告",
        unit: "の明記必須",
        oldValue: "文字を小さくしたりタグに隠して偽装",
        description: isSimpleMode ? "誰が見てもハッキリわかる場所に書かないと違反！" : "文頭や冒頭で一般消費者が広告と一目で認識できること",
        badge: "明確な表記義務",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: FileCheck,
      },
      {
        label: isSimpleMode ? "罰せられるのは誰？" : "規制対象の所在",
        value: "企業側",
        unit: "（広告主の責任）",
        oldValue: "投稿者個人のモラル問題とされていた",
        description: isSimpleMode ? "宣伝を頼んだ会社にすべての責任がある！" : "インフルエンサーではなく発注元事業者が処分の対象",
        badge: "広告主に全責任",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: ShieldAlert,
      },
      {
        label: isSimpleMode ? "摘発事例の推移" : "行政処分件数",
        value: "全国で続々",
        unit: "摘発加速中",
        oldValue: "法制化前は摘発ゼロ件",
        description: isSimpleMode ? "大手クリニックや有名メーカーが次々処分！" : "景品表示法指定後、実際に措置命令が相次ぎ抑止力向上",
        badge: "実効性が向上",
        badgeColor: "bg-purple-100 text-purple-800",
        icon: AlertTriangle,
      },
    ],
    "drone-flying-car-mobility": [
      {
        label: isSimpleMode ? "人の上を飛べるルール" : "航空法改正（レベル4飛行）",
        value: "市街地上空",
        unit: "自律飛行解禁",
        oldValue: "無人地帯での飛行（レベル3）まで",
        description: isSimpleMode ? "住宅地の上を自動で飛べるようになった！" : "有人地帯での目視外自律飛行の国家ライセンス制度創設",
        badge: "レベル4解禁",
        badgeColor: "bg-sky-100 text-sky-800",
        icon: Sparkles,
      },
      {
        label: isSimpleMode ? "荷物が届くまでの時間" : "過疎地・離島配送短縮",
        value: "約 70〜80",
        unit: "% 時間短縮",
        oldValue: "船や軽トラ迂回で半日〜1日以上",
        description: isSimpleMode ? "車で何時間もかかる山奥へ数十分で届く！" : "直線飛行により処方薬や緊急物資を即日デリバリー",
        badge: "最大80%短縮",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "操縦する人の資格" : "国家操縦資格の新設",
        value: "一等・二等",
        unit: "無人航空機操縦士",
        oldValue: "民間の修了証のみ（公的資格なし）",
        description: isSimpleMode ? "国の厳しいテストに受かったプロが操縦する！" : "安全運行を担保する国家ライセンスと型式認証の義務化",
        badge: "国家資格化",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: ShieldCheck,
      },
      {
        label: isSimpleMode ? "一番心配なこと" : "事故・騒音リスクへの懸念",
        value: "落下・騒音",
        unit: "住民の不安",
        oldValue: "実験段階での飛行",
        description: isSimpleMode ? "頭の上に落ちてこないか住民の心配も！" : "パラシュート義務化と飛行航路直下の合意形成が課題",
        badge: "安全対策が必須",
        badgeColor: "bg-rose-100 text-rose-800",
        icon: AlertTriangle,
      },
    ],
    "alien-registration-myna-card": [
      {
        label: isSimpleMode ? "持っているカードの数" : "外国人住民のカード統合",
        value: "2枚 → 1枚",
        unit: "（特定在留カード）",
        oldValue: "在留カードとマイナカードの2枚持ち",
        description: isSimpleMode ? "2枚あったカードが1枚に合体する！" : "在留カードとマイナンバーカードを一体化した新カード",
        badge: "2枚を1枚に統合",
        badgeColor: "bg-teal-100 text-teal-800",
        icon: CreditCard,
      },
      {
        label: isSimpleMode ? "役所に行く回数" : "窓口手続きのワンストップ化",
        value: "市役所訪問",
        unit: "が不要に",
        oldValue: "入管で更新後、さらに市役所へ行く必要あり",
        description: isSimpleMode ? "入国管理局に行けば市役所に行く必要がなくなる！" : "在留更新と同時にマイナンバー期限も自動連動更新",
        badge: "二度手間を解消",
        badgeColor: "bg-blue-100 text-blue-800",
        icon: FileCheck,
      },
      {
        label: isSimpleMode ? "節約できる時間" : "更新手続きの短縮時間",
        value: "約 5時間",
        unit: "節約 / 1回",
        oldValue: "入管待ち時間＋市役所待ち時間で丸1日消費",
        description: isSimpleMode ? "有給休暇を潰さずに手続きが終わる！" : "外国人本人と受け入れ企業の労務コストを大幅カット",
        badge: "約5時間短縮",
        badgeColor: "bg-emerald-100 text-emerald-800",
        icon: Clock,
      },
      {
        label: isSimpleMode ? "ニセモノのカード防止" : "ICチップ暗号照合（JPKI）",
        value: "偽造を撲滅",
        unit: "（1秒で判別）",
        oldValue: "精巧な偽造在留カードでの不法就労が多発",
        description: isSimpleMode ? "スマホをかざすだけでニセモノかすぐ見破れる！" : "公的個人認証と入管データベースのリアルタイム照合",
        badge: "不法就労を防止",
        badgeColor: "bg-purple-100 text-purple-800",
        icon: ShieldCheck,
      },
    ],
  };

  const isUnderDiscussion = policy.status === "discussing" || policy.status === "proposed";
  const defaultHighlights =
    policy.changes && policy.changes.length > 0
      ? policy.changes.slice(0, 4).map((c, idx) => ({
          label: c.topic,
          value: c.highlight || (isUnderDiscussion ? "見直し案" : "新制度"),
          unit: "",
          oldValue: isUnderDiscussion ? `現行: ${c.before}` : `これまで: ${c.before}`,
          description: c.after,
          badge: c.highlight || (isUnderDiscussion ? "審議中" : "新制度"),
          badgeColor: isUnderDiscussion
            ? "bg-amber-100 text-amber-900"
            : idx % 2 === 0
            ? "bg-teal-100 text-teal-800"
            : "bg-emerald-100 text-emerald-800",
          icon: Sparkles,
        }))
      : cardDataMap["child-allowance-expansion"];

  const highlights = cardDataMap[policy.id] || defaultHighlights;

  return (
    <section>
      <div className="flex items-center justify-between mb-3 px-1">
        <h3 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
          <span>{isSimpleMode ? "数字でわかる！重要ポイント" : "4つの主な注目ポイント"}</span>
        </h3>
        <span className="text-xs text-slate-500">ひと目でわかる重要ポイント</span>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        {highlights.map((card, idx) => {
          const Icon = card.icon;
          return (
            <div
              key={idx}
              className="bg-white rounded-2xl border border-slate-200/80 p-4 sm:p-5 shadow-xs hover:shadow-md hover:border-teal-300 transition-all flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between gap-1 mb-2">
                  <span className="p-1.5 rounded-lg bg-slate-100 text-slate-700">
                    <Icon className="w-4 h-4 text-teal-700" />
                  </span>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${card.badgeColor}`}>
                    {card.badge}
                  </span>
                </div>

                <div className="text-xs font-semibold text-slate-500 mb-1">
                  {card.label}
                </div>

                <div className="flex items-baseline gap-0.5 my-1">
                  <span className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
                    {card.value}
                  </span>
                  <span className="text-xs sm:text-sm font-bold text-slate-600">
                    {card.unit}
                  </span>
                </div>
              </div>

              <div className="mt-3 pt-2.5 border-t border-slate-100">
                <div className="text-[11px] text-slate-400 line-through truncate">
                  {card.oldValue}
                </div>
                <div className="text-xs font-bold text-teal-700 mt-0.5 leading-snug">
                  {card.description}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
};
